<?php

namespace ContainerJ3x4kz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C9q37p5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c9q37p5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c9q37p5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fileUploader' => ['services', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
        ], [
            'fileUploader' => 'App\\Service\\FileUploader',
        ]);
    }
}
