<?php

namespace ContainerJBKXysw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZmDpOOhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZmDpOOh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZmDpOOh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fileUploader' => ['services', 'App\\Service\\CandidatFileUploader', 'getCandidatFileUploaderService', true],
        ], [
            'fileUploader' => 'App\\Service\\CandidatFileUploader',
        ]);
    }
}
