<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJBKXysw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJBKXysw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJBKXysw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJBKXysw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJBKXysw\App_KernelDevDebugContainer([
    'container.build_hash' => 'JBKXysw',
    'container.build_id' => '2695c698',
    'container.build_time' => 1743970220,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJBKXysw');
